<?php
include("./classes/db_function.php");
include("./classes/session.php");
include("./classes/function.php");
include("./front/menu.php");
include("./front/header.php"); 
include($fajl);
include("./front/footer.php");
?>